# Generated by Django 4.2.11 on 2026-07-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_must_change_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="temp_password_set_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
