# Generated by Django 4.2.11 on 2026-07-13

import unicodedata

from django.db import migrations, models


def normalized(value):
    return ''.join(
        character
        for character in unicodedata.normalize('NFKD', value)
        if not unicodedata.combining(character) and character.isalnum()
    ).casefold()


def copy_agent_provinces_to_core(apps, schema_editor):
    User = apps.get_model('users', 'User')
    LegacyProvince = apps.get_model('denunciations', 'Province')
    CoreProvince = apps.get_model('core', 'Province')

    core_by_name = {normalized(province.nom): province for province in CoreProvince.objects.all()}
    core_by_code = {province.code.casefold(): province for province in CoreProvince.objects.all()}
    province_mapping = {}
    for legacy_province in LegacyProvince.objects.all():
        province_mapping[legacy_province.pk] = (
            core_by_name.get(normalized(legacy_province.nom))
            or core_by_code.get(legacy_province.code.casefold())
        )

    for user in User.objects.all():
        user.canonical_provinces.add(*[
            province_mapping[legacy_province.pk]
            for legacy_province in user.provinces.all()
            if province_mapping[legacy_province.pk] is not None
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('denunciations', '0007_use_core_province_and_employeur'),
        ('users', '0003_user_temp_password_set_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='canonical_provinces',
            field=models.ManyToManyField(
                blank=True,
                help_text='Provinces assignées à cet agent',
                related_name='canonical_agents',
                to='core.province',
            ),
        ),
        migrations.RunPython(copy_agent_provinces_to_core, migrations.RunPython.noop),
    ]
