# Generated by Django 4.2.11 on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_use_core_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='provinces',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='canonical_provinces',
            new_name='provinces',
        ),
        migrations.AlterField(
            model_name='user',
            name='provinces',
            field=models.ManyToManyField(
                blank=True,
                help_text='Provinces assignées à cet agent',
                related_name='agents',
                to='core.province',
            ),
        ),
    ]
