# Generated by Django 4.2.11 on 2026-05-22 14:52

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('travailleur', 'Travailleur'), ('agent', 'Agent'), ('administrateur', 'Administrateur')], default='travailleur', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('organisation', models.CharField(blank=True, max_length=255)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_inscription'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('secteur', models.CharField(choices=[('agriculture', 'Agriculture'), ('industrie', 'Industrie'), ('commerce', 'Commerce'), ('services', 'Services'), ('sante', 'Santé'), ('education', 'Éducation'), ('energie', 'Énergie'), ('mines', 'Mines'), ('construction', 'Construction'), ('transport', 'Transport'), ('telecommunications', 'Télécommunications'), ('finance', 'Finance'), ('administration', 'Administration Publique'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employeur',
                'verbose_name_plural': 'Employeurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_suivi', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('ville', models.CharField(max_length=100)),
                ('type_incident', models.CharField(choices=[('salaire', 'Non-paiement du salaire'), ('horaires', 'Horaires excessifs'), ('securite', 'Conditions de sécurité insuffisantes'), ('discrimination', 'Discrimination'), ('harcèlement', 'Harcèlement'), ('travail_enfant', 'Travail des enfants'), ('travail_force', 'Travail forcé'), ('congé', 'Refus de congé'), ('cotisations', 'Non-versement des cotisations sociales'), ('licenciement', 'Licenciement abusif'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('analyse', "En cours d'analyse"), ('attente', "En attente d'informations"), ('resolue', 'Résolue'), ('classée', 'Classée sans suite')], db_index=True, default='nouvelle', max_length=20)),
                ('est_anonyme', models.BooleanField(default=True)),
                ('email_contact_anonyme', models.EmailField(blank=True, max_length=254)),
                ('telephone_contact_anonyme', models.CharField(blank=True, max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('est_lu', models.BooleanField(default=False)),
                ('agent_assigné', models.ForeignKey(blank=True, limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_assignés', to=settings.AUTH_USER_MODEL)),
                ('employeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.employeur')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='incidents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'jpg', 'jpeg', 'png', 'gif', 'mp4', 'mp3', 'wav'])])),
                ('nom_original', models.CharField(max_length=255)),
                ('type_fichier', models.CharField(max_length=50)),
                ('taille_fichier', models.BigIntegerField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='core.incident')),
            ],
            options={
                'verbose_name': 'Pièce Jointe',
                'verbose_name_plural': 'Pièces Jointes',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.province'),
        ),
        migrations.AddField(
            model_name='incident',
            name='travailleur',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'travailleur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeur',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeurs', to='core.province'),
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('type_commentaire', models.CharField(choices=[('interne', 'Interne (Agents uniquement)'), ('public', 'Public (Visible au travailleur)')], default='interne', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentaires', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='core.incident')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='provinces',
            field=models.ManyToManyField(blank=True, help_text='Provinces assignées à cet agent', related_name='agents', to='core.province'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='LogAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification_statut', 'Modification de statut'), ('assignation', "Assignation d'agent"), ('ajout_commentaire', 'Ajout commentaire'), ('ajout_piece', 'Ajout pièce jointe'), ('resolution', 'Résolution')], max_length=50)),
                ('description', models.TextField()),
                ('ancienne_valeur', models.TextField(blank=True)),
                ('nouvelle_valeur', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.incident')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_audit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'Audit",
                'verbose_name_plural': "Logs d'Audit",
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['incident', '-date_creation'], name='core_logaud_inciden_30175a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['code_suivi'], name='core_incide_code_su_6b1e54_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['statut', '-date_creation'], name='core_incide_statut_567b75_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['province', 'statut'], name='core_incide_provinc_656292_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeur',
            unique_together={('nom', 'province')},
        ),
    ]
