# Generated by Django 4.2.11 on 2026-06-08 08:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incident",
            name="agent_assigné",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="employeur",
        ),
        migrations.RemoveIndex(
            model_name="incident",
            name="core_incide_provinc_656292_idx",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="province",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="travailleur",
        ),
        migrations.RemoveIndex(
            model_name="logaudit",
            name="core_logaud_inciden_30175a_idx",
        ),
        migrations.RemoveField(
            model_name="logaudit",
            name="incident",
        ),
        migrations.RemoveField(
            model_name="logaudit",
            name="utilisateur",
        ),
        migrations.RemoveField(
            model_name="piecejointe",
            name="incident",
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="provinces",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.DeleteModel(
            name="Commentaire",
        ),
        migrations.DeleteModel(
            name="Incident",
        ),
        migrations.DeleteModel(
            name="LogAudit",
        ),
        migrations.DeleteModel(
            name="PieceJointe",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
