# Generated by Django 4.2.11 on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeur',
            name='adresse_complete',
            field=models.TextField(blank=True),
        ),
    ]
