# Generated by Django 4.2.11 on 2026-05-26 08:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('type_commentaire', models.CharField(choices=[('interne', 'Interne (Agents uniquement)'), ('public', 'Public (Visible au travailleur)')], default='interne', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Employeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('secteur', models.CharField(choices=[('agriculture', 'Agriculture'), ('industrie', 'Industrie'), ('commerce', 'Commerce'), ('services', 'Services'), ('sante', 'Santé'), ('education', 'Éducation'), ('energie', 'Énergie'), ('mines', 'Mines'), ('construction', 'Construction'), ('transport', 'Transport'), ('telecommunications', 'Télécommunications'), ('finance', 'Finance'), ('administration', 'Administration Publique'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employeur',
                'verbose_name_plural': 'Employeurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_suivi', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('ville', models.CharField(max_length=100)),
                ('type_incident', models.CharField(choices=[('salaire', 'Non-paiement du salaire'), ('horaires', 'Horaires excessifs'), ('securite', 'Conditions de sécurité insuffisantes'), ('discrimination', 'Discrimination'), ('harcèlement', 'Harcèlement'), ('travail_enfant', 'Travail des enfants'), ('travail_force', 'Travail forcé'), ('congé', 'Refus de congé'), ('cotisations', 'Non-versement des cotisations sociales'), ('licenciement', 'Licenciement abusif'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('analyse', "En cours d'analyse"), ('attente', "En attente d'informations"), ('resolue', 'Résolue'), ('classée', 'Classée sans suite')], db_index=True, default='nouvelle', max_length=20)),
                ('est_anonyme', models.BooleanField(default=True)),
                ('email_contact_anonyme', models.EmailField(blank=True, max_length=254)),
                ('telephone_contact_anonyme', models.CharField(blank=True, max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('est_lu', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='incidents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'jpg', 'jpeg', 'png', 'gif', 'mp4', 'mp3', 'wav'])])),
                ('nom_original', models.CharField(max_length=255)),
                ('type_fichier', models.CharField(max_length=50)),
                ('taille_fichier', models.BigIntegerField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='denunciations.incident')),
            ],
            options={
                'verbose_name': 'Pièce Jointe',
                'verbose_name_plural': 'Pièces Jointes',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='LogAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation', 'Création'), ('modification_statut', 'Modification de statut'), ('assignation', "Assignation d'agent"), ('ajout_commentaire', 'Ajout commentaire'), ('ajout_piece', 'Ajout pièce jointe'), ('resolution', 'Résolution')], max_length=50)),
                ('description', models.TextField()),
                ('ancienne_valeur', models.TextField(blank=True)),
                ('nouvelle_valeur', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='denunciations.incident')),
            ],
            options={
                'verbose_name': "Log d'Audit",
                'verbose_name_plural': "Logs d'Audit",
                'ordering': ['-date_creation'],
            },
        ),
    ]
