# Generated by Django 4.2.11 on 2026-05-26 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('denunciations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logaudit',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_audit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='agent_assigné',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_assignés', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='employeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='denunciations.employeur'),
        ),
        migrations.AddField(
            model_name='incident',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='denunciations.province'),
        ),
        migrations.AddField(
            model_name='incident',
            name='travailleur',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'travailleur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeur',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeurs', to='denunciations.province'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentaires', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='denunciations.incident'),
        ),
        migrations.AddIndex(
            model_name='logaudit',
            index=models.Index(fields=['incident', '-date_creation'], name='denunciatio_inciden_afe3f1_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['code_suivi'], name='denunciatio_code_su_68c3db_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['statut', '-date_creation'], name='denunciatio_statut_b5fab1_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['province', 'statut'], name='denunciatio_provinc_322f49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeur',
            unique_together={('nom', 'province')},
        ),
    ]
