# Generated by Django 4.2.11 on 2026-06-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("denunciations", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="le_fautif",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="incident",
            name="type_incident_autre",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
