# Generated by Django 4.2.11 on 2026-07-03 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_department"),
        ("denunciations", "0003_incident_le_fautif_incident_type_incident_autre"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="department_assigné",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incidents_assignés_dept",
                to="core.department",
            ),
        ),
    ]
