# Generated by Django 4.2.11 on 2026-07-13

import unicodedata

from django.db import migrations, models
import django.db.models.deletion


def normalized(value):
    return ''.join(
        character
        for character in unicodedata.normalize('NFKD', value)
        if not unicodedata.combining(character) and character.isalnum()
    ).casefold()


def copy_reference_data_to_core(apps, schema_editor):
    LegacyProvince = apps.get_model('denunciations', 'Province')
    LegacyEmployeur = apps.get_model('denunciations', 'Employeur')
    Incident = apps.get_model('denunciations', 'Incident')
    CoreProvince = apps.get_model('core', 'Province')
    CoreEmployeur = apps.get_model('core', 'Employeur')

    provinces_by_name = {}
    provinces_by_code = {}
    for province in CoreProvince.objects.all():
        normalized_name = normalized(province.nom)
        if normalized_name in provinces_by_name:
            raise RuntimeError(
                f"Plusieurs provinces core correspondent à {province.nom!r}."
            )
        provinces_by_name[normalized_name] = province
        provinces_by_code[province.code.casefold()] = province

    province_mapping = {}
    for legacy_province in LegacyProvince.objects.all():
        core_province = provinces_by_name.get(normalized(legacy_province.nom))
        if core_province is None:
            core_province = provinces_by_code.get(legacy_province.code.casefold())
        if core_province is None:
            core_province = CoreProvince.objects.create(
                nom=legacy_province.nom,
                code=legacy_province.code,
                description=legacy_province.description,
            )
            provinces_by_name[normalized(legacy_province.nom)] = core_province
            provinces_by_code[legacy_province.code.casefold()] = core_province
        province_mapping[legacy_province.pk] = core_province

    employeur_mapping = {}
    for legacy_employeur in LegacyEmployeur.objects.select_related('province'):
        province = province_mapping.get(legacy_employeur.province_id)
        core_employeur = CoreEmployeur.objects.filter(
            nom=legacy_employeur.nom,
            province=province,
        ).first()
        if core_employeur is None:
            core_employeur = CoreEmployeur.objects.create(
                nom=legacy_employeur.nom,
                secteur=legacy_employeur.secteur,
                description=legacy_employeur.description,
                ville=legacy_employeur.ville,
                province=province,
                email=legacy_employeur.email,
                telephone=legacy_employeur.telephone,
                adresse_complete=legacy_employeur.adresse_complete,
            )
        employeur_mapping[legacy_employeur.pk] = core_employeur

    for incident in Incident.objects.all():
        incident.canonical_employeur = employeur_mapping[incident.employeur_id]
        incident.canonical_province = province_mapping.get(incident.province_id)
        incident.save(update_fields=['canonical_employeur', 'canonical_province'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employeur_adresse_complete'),
        ('denunciations', '0006_add_employeur_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='canonical_employeur',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='core.employeur',
            ),
        ),
        migrations.AddField(
            model_name='incident',
            name='canonical_province',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='core.province',
            ),
        ),
        migrations.RunPython(copy_reference_data_to_core, migrations.RunPython.noop),
    ]
