# Generated by Django 4.2.11 on 2026-07-13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('denunciations', '0007_use_core_province_and_employeur'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='incident',
            name='denunciatio_provinc_322f49_idx',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='employeur',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='province',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='canonical_employeur',
            new_name='employeur',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='canonical_province',
            new_name='province',
        ),
        migrations.AlterField(
            model_name='incident',
            name='employeur',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='incidents',
                to='core.employeur',
            ),
        ),
        migrations.AlterField(
            model_name='incident',
            name='province',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='incidents',
                to='core.province',
            ),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(
                fields=['province', 'statut'],
                name='denunciatio_provinc_322f49_idx',
            ),
        ),
    ]
