# Generated by Django 4.2.11 on 2026-07-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denunciations', '0008_remove_legacy_province_and_employeur'),
        ('users', '0005_finalize_core_province'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employeur',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
