# Generated by Django 4.2.11 on 2026-08-01 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('denunciations', '0010_ensure_statut_column_exists'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web'), ('other', 'Autre')], default='other', max_length=20)),
                ('code_suivi', models.CharField(blank=True, db_index=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='denunciations.incident')),
            ],
            options={
                'verbose_name': 'Token mobile',
                'verbose_name_plural': 'Tokens mobiles',
                'indexes': [models.Index(fields=['is_active', 'platform'], name='denunciatio_is_acti_da8a0e_idx'), models.Index(fields=['code_suivi', 'is_active'], name='denunciatio_code_su_999bb5_idx')],
            },
        ),
    ]
