# Generated by Django 5.1.6 on 2026-09-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('rccm', models.CharField(blank=True, db_index=True, max_length=100)),
                ('nif', models.CharField(blank=True, db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_site', models.CharField(max_length=255)),
                ('province', models.CharField(choices=[('BAS_UELE', 'Bas-Uele'), ('EQUATEUR', 'Equateur'), ('HAUT_KATANGA', 'Haut-Katanga'), ('HAUT_LOMAMI', 'Haut-Lomami'), ('HAUT_UELE', 'Haut-Uele'), ('ITURI', 'Ituri'), ('KASAÏ', 'Kasaï'), ('KASAÏ_CENTRAL', 'Kasaï-Central'), ('KASAÏ_ORIENTAL', 'Kasaï-Oriental'), ('KINSHASA', 'Kinshasa'), ('KONGO_CENTRAL', 'Kongo-Central'), ('KWANGO', 'Kwango'), ('KWILU', 'Kwilu'), ('LOMAMI', 'Lomami'), ('LUALABA', 'Lualaba'), ('MAI_NDOMBE', 'Mai-Ndombe'), ('MANIEMA', 'Maniema'), ('MONGALA', 'Mongala'), ('NORD_KIVU', 'Nord-Kivu'), ('NORD_UBANGI', 'Nord-Ubangi'), ('SANKURU', 'Sankuru'), ('SUD_KIVU', 'Sud-Kivu'), ('SUD_UBANGI', 'Sud-Ubangi'), ('TANGANYIKA', 'Tanganyika'), ('TSHOPO', 'Tshopo'), ('TSHUAPA', 'Tshuapa')], max_length=30)),
                ('ville_territoire', models.CharField(max_length=255)),
                ('adresse', models.TextField(blank=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etablissements', to='inspections.entreprise')),
            ],
            options={
                'verbose_name': 'Etablissement',
                'verbose_name_plural': 'Etablissements',
                'ordering': ['entreprise__nom', 'nom_site'],
            },
        ),
        migrations.CreateModel(
            name='OrdreDeMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_om', models.CharField(editable=False, max_length=50, unique=True)),
                ('entite_emetteure', models.CharField(choices=[('CABINET', 'Cabinet du Ministre'), ('IGT', 'Inspection Generale du Travail'), ('PROVINCIALE', 'Inspection Provinciale du Travail')], max_length=20)),
                ('scope', models.CharField(choices=[('LOCAL', 'Site specifique'), ('NATIONAL', 'Siege / transversal')], max_length=10)),
                ('objet_mission', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('PROGRAMME', 'Programmee'), ('EN_COURS', 'En cours'), ('FINALISE', 'Finalisee'), ('ANNULE', 'Annulee')], default='PROGRAMME', max_length=15)),
                ('derogation_justification', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordres_de_mission_crees', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordres_de_mission', to='inspections.entreprise')),
                ('etablissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordres_de_mission', to='inspections.etablissement')),
            ],
            options={
                'verbose_name': 'Ordre de mission',
                'verbose_name_plural': 'Ordres de mission',
                'ordering': ['-date_debut', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ordredemission',
            index=models.Index(fields=['entreprise', 'scope', 'statut'], name='inspections_entrepr_b922cf_idx'),
        ),
        migrations.AddIndex(
            model_name='ordredemission',
            index=models.Index(fields=['etablissement', 'statut'], name='inspections_etablis_de7e8a_idx'),
        ),
        migrations.AddIndex(
            model_name='ordredemission',
            index=models.Index(fields=['date_debut', 'date_fin'], name='inspections_date_de_7ea381_idx'),
        ),
    ]